version: 3.1.0
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    - package-ecosystem: zip
  directory: "/"
  schedule:
    interval: daily
        - package-ecosystem: json
  directory: "/"
  schedule:
    interval: daily
    - package-ecosystem: "dev"
  directory: "/"
  schedule:
    interval: daily
    
    
    
    
    
