# Generated by Django 4.0.2 on 2022-03-26 17:53

from django.db import migrations, models

import pictures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "picture",
                    pictures.models.PictureField(
                        aspect_ratios=[None, "1/1", "3/2", "16/9"],
                        upload_to="testapp/profile/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimpleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture_width", models.PositiveIntegerField(null=True)),
                ("picture_height", models.PositiveIntegerField(null=True)),
                (
                    "picture",
                    pictures.models.PictureField(
                        aspect_ratios=[None, "3/2", "16/9"],
                        blank=True,
                        height_field="picture_height",
                        null=True,
                        upload_to="testapp/simplemodel/",
                        width_field="picture_width",
                    ),
                ),
            ],
        ),
    ]
