# Generated by Django 4.0.2 on 2022-03-27 14:37

from django.db import migrations

import pictures.models
from pictures.migrations import AlterPictureField


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        AlterPictureField(  # changed form migrations.AlterField
            model_name="profile",
            name="picture",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/2", "16/9"],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                pixel_densities=[1, 2],
                upload_to="testapp/profile/",
            ),
        ),
    ]
