# Generated by Django 3.2.19 on 2023-06-07 18:06

from django.db import migrations

import pictures.models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_jpegmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/2", "16/9"],
                blank=True,
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                pixel_densities=[1, 2],
                upload_to="testapp/profile/",
            ),
        ),
    ]
