# Generated by Django 4.2.7 on 2024-12-14 13:15

from django.db import migrations

import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0005_alter_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="other_picture",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/2", "16/9"],
                blank=True,
                breakpoints=["small", "medium", "large"],
                container_width=600,
                file_types=["WEBP"],
                grid_columns=12,
                pixel_densities=[1, 2],
                upload_to="testapp/profile/",
                null=True,
            ),
        ),
    ]
