name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uvx --from build pyproject-build --sdist --wheel
      - run: uvx twine check dist/*
      - uses: actions/upload-artifact@v7
        with:
          path: dist/*
  pytest-os:
    name: PyTest
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv run pytest -m "not benchmark"
      - uses: codecov/codecov-action@v6
        with:
          flags: ${{ matrix.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
  pytest-python:
    name: PyTest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        django-version:
          - "5.2" # LTS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv run --group=test --with Django~=${{ matrix.django-version }}.0 pytest -m "not benchmark"
      - uses: codecov/codecov-action@v6
        with:
          flags: py${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
  pytest-django:
    name: PyTest
    strategy:
      matrix:
        python-version:
          - "3.12"
        django-version:
          # LTS gets tested on all OS
          - "6.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv run --group=test --with Django~=${{ matrix.django-version }}.0 pytest -m "not benchmark"
      - uses: codecov/codecov-action@v6
        with:
          flags: dj${{ matrix.django-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
  pytest-extras:
    name: PyTest
    strategy:
      matrix:
        django-version:
          - "5.2" # LTS
        extras:
          - "celery"
          - "dramatiq"
          - "django-rq"
          - "drf"
          - "cleanup"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt update && sudo apt install -y redis-server
        if: matrix.extras == 'dramatiq' || matrix.extras == 'django-rq'
      - uses: astral-sh/setup-uv@v7
      - run: uv run --group=test --extra=${{ matrix.extras }} --with Django~=${{ matrix.django-version }}.0 pytest -m "not benchmark"
      - uses: codecov/codecov-action@v6
        with:
          flags: ${{ matrix.extras }}
          token: ${{ secrets.CODECOV_TOKEN }}
  pytest-benchmark:
    name: PyTest Benchmark
    strategy:
      matrix:
        python-version:
          - "3.14"
        django-version:
          - "6.0"
    permissions:
      actions: read
      contents: read
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/github-script@v7
        id: get-run-id
        with:
          github-token: ${{ github.token }}
          script: |
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              name: 'PyTest Benchmark',
              branch: 'main',
              event: 'push',
            });
            return runs.data.workflow_runs[0].id;
      - uses: actions/download-artifact@v8
        continue-on-error: true
        with:
          name: benchmarks
          path: .benchmarks/Darwin-CPython-${{ matrix.python-version }}-64bit/
          github-token: ${{ github.token }}
          run-id: ${{ steps.get-run-id.outputs.result }}
          merge-multiple: true
      - run: uv run --group=test --with Django~=${{ matrix.django-version }}.0 pytest -m benchmark --benchmark-min-rounds=100 --benchmark-compare --benchmark-compare-fail=mean:0.001
        if: ${{ github.event_name == 'pull_request' }}
      - run: uv run --group=test --with Django~=${{ matrix.django-version }}.0 pytest -m benchmark --benchmark-min-rounds=100
        if: ${{ github.event_name != 'pull_request' }}
      - run: ls -lah .benchmarks/Darwin-CPython-${{ matrix.python-version }}-64bit/
      - uses: actions/upload-artifact@v7
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: benchmarks
          path: .benchmarks/Darwin-CPython-${{ matrix.python-version }}-64bit/*
